services:
  # Backend API
  - type: web
    name: mantes-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
        type: random
      - key: FRONTEND_URL
        sync: false

  # Frontend estático
  - type: static
    name: mantes-web
    env: static
    region: oregon
    plan: free
    buildCommand: echo "Sem build"
    staticPublishPath: .
    envVars:
      - key: NODE_VERSION
        value: 18
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
